/* ============================================================
   Mergent AI — report + Jira export generation
   Produces a self-contained, print-to-PDF-ready HTML report and
   Jira backlog in JSON / CSV. No external dependencies.
   ============================================================ */

export function reportHTML(d) {
  const s = d.summary;
  const phases = d.migration.phases.map((p) => `
    <div class="phase">
      <h3>Phase ${p.n} · ${esc(p.title)} <span class="risk ${p.risk}">${p.risk}</span> <span class="wk">${esc(p.weeks)}</span></h3>
      <ul>${p.steps.map((st) => `<li>${esc(st)}</li>`).join("")}</ul>
    </div>`).join("");
  const risks = d.risks.map((r) => `<tr><td><span class="risk ${r.level}">${r.level}</span></td><td><b>${esc(r.title)}</b><br><span class="muted">${esc(r.impact)}</span></td><td>${esc(r.mitigation)}</td></tr>`).join("");
  const svc = d.services.map((x) => `<tr><td class="mono">${esc(x.id)}</td><td>${esc(x.framework)}</td><td class="mono">${x.endpoints}</td><td class="mono">${esc(x.db || "—")}</td><td class="mono">${esc(x.target || "—")}</td></tr>`).join("");

  return `<!doctype html><html><head><meta charset="utf-8"><title>Mergent Migration Report — ${esc(d.repo.name)}</title>
<style>
  *{box-sizing:border-box} body{font-family:-apple-system,Segoe UI,Roboto,sans-serif;color:#16181d;max-width:880px;margin:40px auto;padding:0 24px;line-height:1.5}
  h1{font-size:30px;margin:0 0 4px} .sub{color:#667;margin-bottom:24px}
  .kpis{display:flex;gap:14px;flex-wrap:wrap;margin:18px 0 28px}
  .kpi{border:1px solid #e3e6ea;border-radius:12px;padding:12px 16px;min-width:120px}
  .kpi .v{font-size:24px;font-weight:700} .kpi .k{color:#667;font-size:12px;text-transform:uppercase;letter-spacing:.04em}
  h2{margin-top:34px;border-bottom:2px solid #eef;padding-bottom:6px}
  table{width:100%;border-collapse:collapse;margin:12px 0;font-size:14px} td,th{border:1px solid #e3e6ea;padding:8px 10px;text-align:left;vertical-align:top}
  th{background:#f6f8fa} .mono{font-family:ui-monospace,Menlo,monospace;font-size:13px} .muted{color:#778}
  .risk{display:inline-block;padding:1px 8px;border-radius:20px;font-size:11px;font-weight:700;text-transform:uppercase}
  .risk.high{background:#ffe3e3;color:#b00020}.risk.med{background:#fff3d6;color:#9a6700}.risk.low{background:#e3f3e8;color:#1a7f37}
  .phase{border:1px solid #e3e6ea;border-radius:12px;padding:12px 16px;margin:12px 0} .wk{color:#778;font-size:13px;font-weight:400;margin-left:6px}
  footer{margin-top:40px;color:#889;font-size:12px;border-top:1px solid #eee;padding-top:12px}
</style></head><body>
  <h1>Migration Report</h1>
  <div class="sub">${esc(d.repo.name)} · ${d.repo.services} services · ${d.repo.files} files · generated by Mergent AI (${esc(s.mode || "deterministic")} mode)</div>
  <div class="kpis">
    <div class="kpi"><div class="v">${s.servicesBefore} → ${s.servicesAfter}</div><div class="k">services</div></div>
    <div class="kpi"><div class="v">${s.depsBefore} → ${s.depsAfter}</div><div class="k">dependencies</div></div>
    <div class="kpi"><div class="v">${s.dupApis} → 0</div><div class="k">duplicate APIs</div></div>
    <div class="kpi"><div class="v">${s.dbBefore} → ${s.dbAfter}</div><div class="k">databases</div></div>
    <div class="kpi"><div class="v">${s.risksHigh}</div><div class="k">high risks</div></div>
  </div>

  <h2>01 · Executive summary</h2>
  <p>${esc(d.migration.rationale)}</p>

  <h2>02 · Services</h2>
  <table><thead><tr><th>Service</th><th>Framework</th><th>Endpoints</th><th>Database</th><th>Consolidates into</th></tr></thead><tbody>${svc}</tbody></table>

  <h2>03 · Sequencing (${d.migration.phases.length} phases · ${esc(d.migration.totalWeeks)} wks)</h2>
  ${phases}

  <h2>04 · Rollback strategy</h2>
  <p>Each phase is independently reversible. Keep retired services deployed but de-routed at the gateway until the merged service has run clean for one release cycle; flip routes back on regression. Database merges run dual-write → backfill → verify → cut-read, so a rollback is a read-source switch, not a restore.</p>

  <h2>05 · Risk register (${s.risksHigh} high · ${s.risksMed} medium · ${s.risksLow} low)</h2>
  <table><thead><tr><th>Level</th><th>Risk &amp; impact</th><th>Mitigation</th></tr></thead><tbody>${risks}</tbody></table>

  <footer>Generated by Mergent AI · hybrid deterministic-parse + LLM-reason pipeline · ${new Date().toISOString().slice(0, 10)}</footer>
</body></html>`;
}

export function reportText(d) {
  const s = d.summary;
  const L = [];
  L.push(`MERGENT MIGRATION REPORT — ${d.repo.name}`);
  L.push("=".repeat(56));
  L.push(`${s.servicesBefore} → ${s.servicesAfter} services · ${s.depsBefore} → ${s.depsAfter} deps · ${s.dupApis} → 0 dup APIs · ${s.dbBefore} → ${s.dbAfter} DBs`);
  L.push("");
  L.push("01 EXECUTIVE SUMMARY");
  L.push(d.migration.rationale);
  L.push("");
  L.push(`02 SEQUENCING (${d.migration.phases.length} phases · ${d.migration.totalWeeks} wks)`);
  for (const p of d.migration.phases) {
    L.push(`  Phase ${p.n}: ${p.title} [${p.risk}] (${p.weeks})`);
    for (const st of p.steps) L.push(`    - ${st}`);
  }
  L.push("");
  L.push(`03 TOP RISKS (${s.risksHigh} high)`);
  for (const r of d.risks.filter((x) => x.level === "high")) L.push(`  ! ${r.title} — ${r.mitigation}`);
  L.push("");
  L.push(`[ generated by Mergent AI · ${d.repo.files} files analyzed · ${s.mode || "deterministic"} mode ]`);
  return L.join("\n");
}

export function jiraJSON(d) {
  return JSON.stringify(
    d.jira.map((t) => ({
      key: t.key,
      fields: { summary: t.title, description: t.desc, issuetype: "Task", priority: t.priority, customfield_storypoints: t.points, epic: t.epic, depends_on: t.deps },
    })),
    null, 2
  );
}

export function jiraCSV(d) {
  const head = "Key,Summary,Epic,Priority,Points,Depends On";
  return head + "\n" + d.jira.map((t) => [t.key, q(t.title), t.epic, t.priority, t.points, q((t.deps || []).join(" "))].join(",")).join("\n");
}

const q = (s) => `"${String(s).replace(/"/g, '""')}"`;
const esc = (s) => String(s == null ? "" : s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
